Repository TrapTeamCCNZ/TrapTeamMainSite, pull requests merged in 2019-06, with the labels that each got.

#22 Ttaccessoffline do not touch
  404.html
  accessbt/access.svg
  accessbt/index.html
  accessbt/loader.svg
  app/index.html
  auth.html
  index.html
Labels: size/XXL

#26 Unified UI
  404.html
  about.html
  git.html
  index.html
Labels: size/M

#50 New Working Functions
  blog.html
  functions/index.js
  functions/package.json
  git.html
Labels: bug, enhancement, size/L
